version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/home/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
    container_name: postgres_djangopj
    restart : always
    ports:
      - "5432:5432"
  web:
    build:
      dockerfile: Dockerfile
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        echo yes | python manage.py collectstatic
        gunicorn djangopj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/djangopj
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db